import OpenAI from 'openai';
const openai=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
function isCifraClubUrl(value){try{const u=new URL(value);return u.hostname==='www.cifraclub.com.br'||u.hostname==='cifraclub.com.br';}catch{return false;}}
function htmlToStructuredText(html){return html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<br\s*\/?>(?=.)/gi,'\n').replace(/<\/(p|div|li|tr|section|article|h[1-6])\s*>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/\r/g,'').split('\n').map(line=>line.replace(/\s+/g,' ').trim()).filter(Boolean).join('\n');}
function normalizeBlocks(data){if(!Array.isArray(data?.blocks))return data;return {...data,blocks:data.blocks.map(block=>{if(!Array.isArray(block.lines)||!block.lines.length)return block;const lines=block.lines.map(line=>({chords:typeof line?.chords==='string'?line.chords.trim():'',lyric:typeof line?.lyric==='string'?line.lyric.trim():''})).filter(line=>line.chords||line.lyric);return {...block,lines,anchor:[...lines].find(line=>line.lyric)?.lyric||block.anchor||''};})};}
export async function POST(request){try{const {url}=await request.json();if(!isCifraClubUrl(url))return Response.json({error:'Cole um link válido do Cifra Club.'},{status:400});if(!process.env.OPENAI_API_KEY)return Response.json({error:'OPENAI_API_KEY ainda não foi configurada na Vercel.'},{status:500});const page=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 (compatible; CifrasPDF/1.0)'},next:{revalidate:0}});if(!page.ok)throw new Error('O Cifra Club não permitiu acessar essa página agora.');const text=htmlToStructuredText(await page.text()).slice(0,60000);const completion=await openai.chat.completions.create({model:'gpt-4o-mini',response_format:{type:'json_object'},messages:[{role:'system',content:`Organize a cifra para visualização e PDF. Retorne JSON válido com title, artist, key e blocks.

TOM ORIGINAL É OBRIGATÓRIO: identifique o tom original exibido na página do Cifra Club. Preserve esse tom e os acordes originais. NÃO faça transposição. NÃO use parâmetros como key=3 da URL como tom da música. Se a página disser "Tom: E", retorne key:"E" e mantenha os acordes em E. Se não tiver certeza do tom, key:"".

Cada block é uma parte natural (intro, verso, pré-refrão, refrão, ponte etc.). Cada block deve ter selected=true e lines. Respeite as quebras musicais originais, não junte linhas diferentes, não crie linhas por largura. Mantenha acordes na ordem e tonalidade original. Use somente a frase inicial curta de cada trecho como lyric/anchor. Não invente, corrija ou transponha acordes.`},{role:'user',content:`URL: ${url}\nConteúdo original estruturado:\n${text}`} ]});return Response.json(normalizeBlocks(JSON.parse(completion.choices[0].message.content)));}catch(error){return Response.json({error:error?.message||'Erro ao processar a cifra.'},{status:500});}}
