import pdfParse from 'pdf-parse';

const API_FALLBACK = 'https://cifraclub-api.vercel.app/api/cifra';
const NOTE_VALUES = { C:0,'C#':1,Db:1,D:2,'D#':3,Eb:3,E:4,F:5,'F#':6,Gb:6,G:7,'G#':8,Ab:8,A:9,'A#':10,Bb:10,B:11 };
const SHARPS=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
const FLATS=['C','Db','D','Eb','E','F','Gb','G','Ab','A','Bb','B'];
const CHORD_RE=/^[A-Ga-g](?:#|b)?(?:maj|min|m|dim|aug|sus|add)?(?:2|4|5|6|7|9|11|13)?(?:b5|#5)?(?:\/[A-Ga-g](?:#|b)?)?$/;

function slug(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9-]/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'');}
function isCifraClubUrl(value){try{return ['www.cifraclub.com.br','cifraclub.com.br'].includes(new URL(value).hostname)}catch{return false}}
function getArtistSongFromUrl(value){const u=new URL(value);const parts=u.pathname.split('/').filter(Boolean).map(decodeURIComponent);const ignored=new Set(['letra','imprimir','tab','tabs','guitarra','violao','bateria']);const useful=parts.filter(p=>!ignored.has(p.toLowerCase()));return useful.length>=2?{artist:slug(useful[0]),song:slug(useful[1])}:null;}
function htmlToText(html){return String(html||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<br\s*\/?>(?=.)/gi,'\n').replace(/<\/(p|div|li|tr|section|article|h[1-6])\s*>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&#x27;/gi,"'").replace(/\r/g,'').split('\n').map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean).join('\n');}
async function fetchCifraContent(url){const source=getArtistSongFromUrl(url);if(source){try{const r=await fetch(`${API_FALLBACK}?artist=${encodeURIComponent(source.artist)}&song=${encodeURIComponent(source.song)}`,{headers:{Accept:'application/json'},cache:'no-store'});if(r.ok){const d=await r.json();if(Array.isArray(d?.cifra)&&d.cifra.length)return {text:d.cifra.join('\n'),title:d.name||source.song,artist:d.artist||source.artist};}}catch{}}
const page=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 (compatible; CifrasPDF/1.0)'},cache:'no-store'});if(!page.ok)throw new Error('O Cifra Club não permitiu acessar essa página agora.');return {text:htmlToText(await page.text()).slice(0,60000),title:'',artist:''};}
async function readUploadedFile(file){const name=(file.name||'arquivo').toLowerCase(),type=(file.type||'').toLowerCase();const bytes=Buffer.from(await file.arrayBuffer());if(bytes.length>10*1024*1024)throw new Error('O arquivo deve ter no máximo 10 MB.');if(type==='application/pdf'||name.endsWith('.pdf')){const parsed=await pdfParse(bytes);return {text:String(parsed.text||'').slice(0,60000),title:file.name.replace(/\.pdf$/i,''),artist:''};}if(type.includes('html')||/\.(html?|htm)$/i.test(name))return {text:htmlToText(bytes.toString('utf8')).slice(0,60000),title:file.name.replace(/\.(html?|htm)$/i,''),artist:''};if(type.startsWith('text/')||/\.(txt|md|csv)$/i.test(name))return {text:bytes.toString('utf8').slice(0,60000),title:file.name.replace(/\.(txt|md|csv)$/i,''),artist:''};throw new Error('Formato não suportado. Envie PDF, TXT ou HTML.');}
function chordTokens(line){const s=String(line||'').trim();if(!s)return [];const parts=s.replace(/[|,;]+/g,' ').split(/\s+/).filter(Boolean);if(parts.length&&parts.every(x=>CHORD_RE.test(x)))return parts;const compact=s.replace(/[\s|,;]+/g,'');const out=[];let pos=0;const re=/[A-Ga-g](?:#|b)?(?:maj|min|m|dim|aug|sus|add)?(?:2|4|5|6|7|9|11|13)?(?:b5|#5)?(?:\/[A-Ga-g](?:#|b)?)?/g;let m;while((m=re.exec(compact))!==null){if(m.index!==pos)return [];out.push(m[0]);pos=re.lastIndex;}return pos===compact.length?out:[];}
function isChordLine(line){return chordTokens(line).length>0;}
function normalizeChordLine(line){const t=chordTokens(line);return t.length?t.join('  '):String(line||'').trim();}
function cleanAnchor(line){return String(line||'').replace(/^[\s•*-]+/,'').replace(/\.\.\.$/,'').trim();}
function detectKey(blocks){const count={};for(const b of blocks){for(const line of b.lines||[]){for(const chord of chordTokens(line.chords)){const root=(chord.match(/^([A-Ga-g](?:#|b)?)/)||[])[1];if(root){const normalized=root[0].toUpperCase()+root.slice(1);const n=NOTE_VALUES[normalized];if(n!=null){const key=SHARPS[n];count[key]=(count[key]||0)+1;}}}}}return Object.entries(count).sort((a,b)=>b[1]-a[1])[0]?.[0]||'';}
function structureRawText(text){const raw=String(text||'').replace(/\r/g,'').split('\n').map(x=>x.trim()).filter(Boolean);const blocks=[];let section='';let pendingChords=[];let pendingLyrics=[];const flush=()=>{if(!pendingChords.length){pendingLyrics=[];return;}const lines=[...pendingChords.map(chords=>({chords,lyric:''})),...pendingLyrics.map(lyric=>({chords:'',lyric}))];blocks.push({selected:true,section,anchor:cleanAnchor(pendingLyrics[0]||''),chords:pendingChords.slice(),lines});pendingChords=[];pendingLyrics=[];};for(const line of raw){if(/^\[[^\]]+\]$/.test(line)){flush();section=line.slice(1,-1).trim();continue;}if(isChordLine(line)){if(pendingLyrics.length)flush();pendingChords.push(normalizeChordLine(line));continue;}if(pendingChords.length)pendingLyrics.push(line);}flush();return blocks;}
function normalizeTextBlocks(text){return structureRawText(text).filter(b=>b.lines.length);}

export async function POST(request){try{let url='',content=null;const ct=request.headers.get('content-type')||'';if(ct.includes('multipart/form-data')){const form=await request.formData();url=String(form.get('url')||'').trim();const file=form.get('file');if(file&&typeof file!=='string')content=await readUploadedFile(file);}else{const body=await request.json();url=String(body.url||'').trim();}
if(!content){if(!isCifraClubUrl(url))return Response.json({error:'Cole um link válido do Cifra Club ou envie um arquivo.'},{status:400});content=await fetchCifraContent(url);}
if(!content.text||content.text.trim().length<20)throw new Error('Não encontrei texto suficiente para montar a cifra. Se for um PDF escaneado, envie uma versão com texto selecionável.');
const blocks=normalizeTextBlocks(content.text);if(!blocks.length)throw new Error('A cifra foi lida, mas não encontrei linhas de acordes.');
const key=detectKey(blocks);return Response.json({title:content.title||'',artist:content.artist||'',key,originalKey:key,blocks});
}catch(error){return Response.json({error:error?.message||'Erro ao processar a cifra.'},{status:500});}}
