'use client';
import { useState } from 'react';
import { jsPDF } from 'jspdf';

export default function Home() {
  const [url,setUrl]=useState(''); const [loading,setLoading]=useState(false); const [blocks,setBlocks]=useState([]); const [error,setError]=useState('');
  async function processCifra(){setError('');setLoading(true);try{const r=await fetch('/api/process',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});const d=await r.json();if(!r.ok)throw Error(d.error||'Não foi possível processar.');setBlocks(d.blocks||[]);}catch(e){setError(e.message)}finally{setLoading(false)}}
  function toggle(i){setBlocks(p=>p.map((b,n)=>n===i?{...b,selected:!b.selected}:b))} function selectAll(v){setBlocks(p=>p.map(b=>({...b,selected:v})))}
  function pdf(){const s=blocks.filter(b=>b.selected);if(!s.length)return;const d=new jsPDF({unit:'mm',format:'a4'});d.setFont('helvetica','bold');d.setFontSize(20);d.text(blocks[0]?.title||'Cifra',15,18);d.setFont('helvetica','normal');d.setFontSize(11);d.text(blocks[0]?.artist||'',15,25);let y=38;s.forEach(b=>{if(y>275){d.addPage();y=18}d.setFont('helvetica','bold');d.setFontSize(12);d.text(b.chords.join('  '),15,y);d.setFont('helvetica','normal');d.setFontSize(11);d.text((b.anchor||'')+'...',15,y+7);y+=20});d.save(((blocks[0]?.title||'cifra').replace(/[^a-z0-9]+/gi,'-').toLowerCase())+'.pdf')}
  return <main className="wrap"><header><div className="logo">♪</div><div><h1>Cifras</h1><p>Monte sua cifra personalizada em PDF</p></div></header><section className="card"><label>Link do Cifra Club</label><div className="row"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Cole aqui o link da cifra..."/><button onClick={processCifra} disabled={loading||!url}>{loading?'Processando...':'Processar cifra'}</button></div>{error&&<div className="error">{error}</div>}</section>{blocks.length>0&&<section className="card"><div className="toolbar"><div><h2>{blocks[0].title}</h2><p>{blocks[0].artist}</p></div><div><button className="ghost" onClick={()=>selectAll(true)}>Selecionar todos</button><button className="ghost" onClick={()=>selectAll(false)}>Limpar</button></div></div><p className="hint">Marque somente os trechos que você quer no PDF.</p><div className="blocks">{blocks.map((b,i)=><label className={`block ${b.selected?'selected':''}`} key={i}><input type="checkbox" checked={!!b.selected} onChange={()=>toggle(i)}/><div><div className="chords">{b.chords.join('  ')}</div><div className="anchor">{b.anchor}...</div></div></label>)}</div><button className="pdf" onClick={pdf}>Gerar PDF dos selecionados</button></section>}</main>
}
