'use client';
import { useMemo, useRef, useState } from 'react';
import { NOTES, FLAT_NOTES, semitonesBetween, transposeLine } from '../lib/transpose';

function blockChordText(block){return Array.isArray(block.lines)&&block.lines.length?block.lines.map(l=>l.chords||'').filter(Boolean).join('\n'):Array.isArray(block.chords)?block.chords.join('  '):block.chords||'';}
function blockLyricText(block){return typeof block.anchor==='string'&&block.anchor?block.anchor.replace(/\.\.\.$/,''):block.lines?.find(l=>l.lyric)?.lyric||'';}
function transposeBlocks(blocks,semitones,preferFlats){return blocks.map(b=>({...b,chords:Array.isArray(b.chords)?b.chords.map(x=>transposeLine(x,semitones,preferFlats)):b.chords,lines:Array.isArray(b.lines)?b.lines.map(l=>({...l,chords:l.chords?transposeLine(l.chords,semitones,preferFlats):''})):b.lines}));}
function BlockPreview({block}){return <div className="music-lines">{block.section&&<div className="section-label">[{block.section}]</div>}{(block.lines||[]).filter(l=>l.chords).map((l,i)=><div className="music-line" key={i}><div className="line-chords">{l.chords}</div></div>)}{blockLyricText(block)&&<div className="line-lyric block-anchor">{blockLyricText(block)}...</div>}</div>}
function applyEdits(block,chordsText,lyricText){const chordLines=chordsText.split('\n').map(x=>x.trim()).filter(Boolean);const lyric=lyricText.trim();return {...block,anchor:lyric,chords:chordLines,lines:[...chordLines.map(chords=>({chords,lyric:''})),...(lyric?[{chords:'',lyric}]:[])],_editText:chordsText};}
function SelectedSong({song}){let lastSection='';return <section className="print-song"><h2>{song.title}</h2>{song.artist&&<p className="print-artist">{song.artist}</p>}{song.key&&<p className="print-key">Tom: {song.key}</p>}{song.blocks.map((b,i)=>{const show=!!b.section&&b.section!==lastSection;lastSection=b.section||lastSection;return <div className="print-block" key={i}>{show&&<h3 className="print-section">[{b.section}]</h3>}{b.lines?.map((l,j)=><div className="print-line" key={j}>{l.chords&&<div className="print-chords">{l.chords}</div>}{l.lyric&&<div className="print-lyric">{l.lyric}</div>}</div>)}</div>})}</section>}

export default function Home(){
 const[url,setUrl]=useState(''),[file,setFile]=useState(null),[loading,setLoading]=useState(false),[blocks,setBlocks]=useState([]),[error,setError]=useState(''),[editing,setEditing]=useState(null),[history,setHistory]=useState({}),[songs,setSongs]=useState([]),[songInfo,setSongInfo]=useState({title:'',artist:'',key:'',originalKey:''}),[targetKey,setTargetKey]=useState(''),[transposeSteps,setTransposeSteps]=useState(0);const fileRef=useRef(null);
 const displayedBlocks=useMemo(()=>transposeBlocks(blocks,transposeSteps,/b$/.test(targetKey)),[blocks,transposeSteps,targetKey]);
 const currentKey=useMemo(()=>{const base=songInfo.originalKey||songInfo.key;if(!base)return '';const idx=NOTES.indexOf(base);if(idx<0)return base;return (targetKey.includes('b')?FLAT_NOTES:NOTES)[(idx+transposeSteps+120)%12]},[songInfo.originalKey,songInfo.key,targetKey,transposeSteps]);
 async function processCifra(){setError('');if(!url.trim()&&!file){setError('Cole um link ou envie um arquivo.');return;}setLoading(true);try{const form=new FormData();if(url.trim())form.append('url',url.trim());if(file)form.append('file',file);const r=await fetch('/api/process',{method:'POST',body:form});const d=await r.json();if(!r.ok)throw Error(d.error||'Não foi possível processar.');setBlocks(d.blocks||[]);setSongInfo({title:d.title||'',artist:d.artist||'',key:d.key||'',originalKey:d.originalKey||d.key||''});setTargetKey(d.key||'');setTransposeSteps(0);setEditing(null);setHistory({});}catch(e){setError(e.message)}finally{setLoading(false)}}
 function resetSource(){setUrl('');setFile(null);if(fileRef.current)fileRef.current.value='';}
 function toggle(i){setBlocks(p=>p.map((b,n)=>n===i?{...b,selected:!b.selected}:b))}function selectAll(v){setBlocks(p=>p.map(b=>({...b,selected:v})))}
 function updateBlock(i,changes){setHistory(h=>({...h,[i]:[...(h[i]||[]),blocks[i]].slice(-50)}));setBlocks(p=>p.map((b,n)=>n===i?{...b,...changes}:b))}
 function undoBlock(i){const s=history[i]||[];if(!s.length)return;setBlocks(p=>p.map((b,n)=>n===i?s[s.length-1]:b));setHistory(h=>({...h,[i]:s.slice(0,-1)}));}
 function addChordLine(i){const b=blocks[i];const current=b._editText??blockChordText(b);updateBlock(i,applyEdits(b,current+(current?'\n':''),blockLyricText(b)))}
 function changeKey(key){if(!songInfo.originalKey)return;const delta=semitonesBetween(songInfo.originalKey,key);setTargetKey(key);setTransposeSteps(delta)}
 function stepKey(delta){const base=songInfo.originalKey||songInfo.key;if(!base)return;const idx=NOTES.indexOf(base);const newIndex=(idx+delta+120)%12;const flats=targetKey.includes('b');const key=(flats?FLAT_NOTES:NOTES)[newIndex];setTargetKey(key);setTransposeSteps(delta)}
 function restoreKey(){setTargetKey(songInfo.originalKey);setTransposeSteps(0)}
 function advanceSong(){const selected=displayedBlocks.filter(b=>b.selected);if(!selected.length){setError('Selecione pelo menos um trecho antes de adicionar a música.');return;}setSongs(p=>[...p,{...songInfo,key:currentKey||songInfo.originalKey,title:songInfo.title||`Música ${p.length+1}`,blocks:selected.map(b=>({...b,selected:true}))}]);setBlocks([]);setEditing(null);setHistory({});setSongInfo({title:'',artist:'',key:'',originalKey:''});setTargetKey('');setTransposeSteps(0);resetSource();setError('');window.scrollTo({top:0,behavior:'smooth'})}
 function pdf(){if(songs.length)window.print()}
 return <main className="wrap">
  <header><div className="logo">♪</div><div><h1>Cifras</h1><p>Monte sua cifra personalizada em PDF</p></div></header>
  <section className="card no-print"><label>Como você quer adicionar a cifra?</label><div className="source-options"><div className="source-box"><label>🔗 Link do Cifra Club</label><input value={url} onChange={e=>{setUrl(e.target.value);if(e.target.value)setFile(null)}} placeholder="Cole aqui o link da cifra..."/></div><div className="source-divider">ou</div><div className="source-box file-source"><label>📄 Arquivo da cifra</label><input ref={fileRef} type="file" accept=".pdf,.txt,.html,.htm,.md,.csv,application/pdf,text/plain,text/html" onChange={e=>{const f=e.target.files?.[0]||null;setFile(f);if(f)setUrl('')}}/>{file?<div className="selected-file">✓ {file.name}</div>:<div className="file-help">PDF, TXT ou HTML — até 10 MB</div>}</div></div><div className="row process-row"><button onClick={processCifra} disabled={loading||(!url.trim()&&!file)}>{loading?'Processando...':'Processar cifra'}</button></div>{error&&<div className="error">{error}</div>}</section>
  {songs.length>0&&<section className="card no-print song-counter"><strong>{songs.length} {songs.length===1?'música preparada':'músicas preparadas'} para o PDF</strong><div className="song-list">{songs.map((s,i)=><div className="song-item" key={i}><span>{i+1}. {s.title} {s.key&&` — Tom ${s.key}`}</span><button className="remove-song" onClick={()=>setSongs(p=>p.filter((_,n)=>n!==i))}>Remover</button></div>)}</div><button className="pdf" onClick={pdf}>Gerar PDF com {songs.length} {songs.length===1?'música':'músicas'}</button></section>}
  {blocks.length>0&&<section className="card no-print"><div className="toolbar"><div><h2>{songInfo.title||'Cifra'}</h2>{songInfo.artist&&<p>{songInfo.artist}</p>}<p><strong>Tom original: {songInfo.originalKey||'—'}</strong>{currentKey&&currentKey!==songInfo.originalKey&&<> · Atual: <strong>{currentKey}</strong></>}</p></div><div><button className="ghost" onClick={()=>selectAll(true)}>Selecionar todos</button><button className="ghost" onClick={()=>selectAll(false)}>Limpar</button></div></div>
   <div className="song-meta-editor"><div><label>Nome da música</label><input value={songInfo.title} onChange={e=>setSongInfo(p=>({...p,title:e.target.value}))}/></div><div><label>Tom</label><div className="transpose-controls"><button onClick={()=>stepKey(-1)} title="Baixar 1 semitom">−</button><select value={currentKey||''} onChange={e=>changeKey(e.target.value)}><option value="">Selecione</option>{[...NOTES,...FLAT_NOTES.filter(x=>!NOTES.includes(x))].map(k=><option key={k} value={k}>{k}</option>)}</select><button onClick={()=>stepKey(1)} title="Subir 1 semitom">+</button></div><div className="transpose-actions"><button className="restore-key" onClick={restoreKey} disabled={transposeSteps===0}>↺ Restaurar</button><span>Transposição instantânea</span></div></div></div>
   <div className="blocks">{displayedBlocks.map((b,i)=>{const base=blocks[i];const chordsText=base._editText??blockChordText(base),lyricText=blockLyricText(base),isEditing=editing===i,hasUndo=(history[i]||[]).length>0;return <div className={`block ${b.selected?'selected':''} ${isEditing?'editing':''}`} key={i}><input type="checkbox" checked={!!b.selected} onChange={()=>toggle(i)}/><div className="block-content">{isEditing?<div className="editor"><div className="editor-field"><label>Acordes</label><textarea value={chordsText} onChange={e=>updateBlock(i,applyEdits(base,e.target.value,lyricText))} rows={Math.max(3,chordsText.split('\n').length+1)}/><div className="editor-help">Uma linha = uma linha de acordes. A transposição é aplicada automaticamente.</div><button className="add-line-button" onClick={()=>addChordLine(i)}>＋ Adicionar linha de acordes</button></div><div className="editor-field"><label>Início do verso</label><input value={lyricText} onChange={e=>updateBlock(i,applyEdits(base,chordsText,e.target.value))}/></div><div className="editor-actions"><button className="undo-button" onClick={()=>undoBlock(i)} disabled={!hasUndo}>↶ Desfazer</button><button className="save-edit" onClick={()=>setEditing(null)}>Concluir edição</button></div></div>:<BlockPreview block={b}/>}</div>{!isEditing&&<button className="edit-button" onClick={()=>setEditing(i)}>Editar</button>}</div>})}</div><button className="advance" onClick={advanceSong}>Adicionar ao PDF e avançar para próxima música</button>
  </section>}
  <div className="print-document">{songs.map((s,i)=><SelectedSong song={s} key={i}/>)}</div>
 </main>;
}
