'use client'
import {useState} from 'react'
import {jsPDF} from 'jspdf'
type Block={id:number,phrase:string,chords:string}
const demo:Block[]=[{id:1,phrase:'Na presença dos homens...',chords:'C  F  Em  Am  Dm7  Em  F'},{id:2,phrase:'Sobre toda terra...',chords:'G  C  F  G  C'},{id:3,phrase:'Tua alegria...',chords:'G  C  F  G  C'},{id:4,phrase:'Deus de maravilhas...',chords:'G  C  A7  Dm7  Bb2  Dm7  E  Am'},{id:5,phrase:'Eu entro na Tua presença...',chords:'Dm7  Am  Em  Am'},{id:6,phrase:'O som da festa vai subir...',chords:'F  C  Em  Am  F  C  G'}]
export default function Home(){const [url,setUrl]=useState('');const [blocks,setBlocks]=useState<Block[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
async function process(){setLoading(true);setError('');try{const r=await fetch('/api/process',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});const d=await r.json();if(!r.ok)throw Error(d.error||'Não foi possível processar.');setBlocks(d.blocks)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
function toggle(id:number){setBlocks(b=>b.map(x=>x.id===id?{...x,selected:!(x as any).selected}:x))}
function pdf(){const selected=blocks.filter((x:any)=>x.selected);if(!selected.length)return;const doc=new jsPDF();doc.setFontSize(18);doc.text('Cifra selecionada',20,20);let y=35;selected.forEach(x=>{doc.setFontSize(13);doc.text(x.phrase,20,y);y+=7;doc.setFontSize(14);doc.text(x.chords,20,y);y+=12;if(y>275){doc.addPage();y=20}});doc.save('cifra-selecionada.pdf')}
return <main className="wrap"><header><div className="logo">♪</div><div><h1>Cifras</h1><p>Separe os trechos da cifra e gere seu PDF.</p></div></header><section className="card"><label>Link do Cifra Club</label><div className="row"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Cole aqui o link da cifra..."/><button onClick={process} disabled={!url||loading}>{loading?'Processando...':'Separar cifra'}</button></div><p className="hint">A IA organiza os acordes em blocos e mostra apenas o início de cada trecho.</p>{error&&<div className="error">{error}</div>}</section>{blocks.length>0&&<section className="card"><div className="toolbar"><div><h2>Escolha os trechos</h2><p>{blocks.filter((x:any)=>x.selected).length} selecionados</p></div><div><button className="ghost" onClick={()=>setBlocks(b=>b.map(x=>({...x,selected:true})))}>Selecionar todos</button><button className="ghost" onClick={()=>setBlocks(b=>b.map(x=>({...x,selected:false})))}>Limpar</button></div></div>{blocks.map(x=><div key={x.id} className={'block '+((x as any).selected?'selected':'')} onClick={()=>toggle(x.id)}><input type="checkbox" checked={!!(x as any).selected} onChange={()=>toggle(x.id)} onClick={e=>e.stopPropagation()}/><div><div className="chords">{x.chords}</div><div className="anchor">{x.phrase}</div></div></div>)}<button className="pdf" onClick={pdf}>Gerar PDF dos selecionados</button></section>}</main>}
